# Generated by Django 2.2 on 2020-01-05 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=100)),
                ('date_of_birth', models.DateField(auto_now=True)),
                ('club', models.CharField(choices=[('BSKU', 'Bangladesh Shitoryu Karate-do Union'), ('SKAA', 'Arrianna Academy')], max_length=100)),
                ('team', models.CharField(choices=[('AVDP', 'Bangladesh Ansar & VDP'), ('BA', 'Bangladesh Army')], max_length=100)),
                ('gold', models.IntegerField(default=0)),
                ('silver', models.IntegerField(default=0)),
                ('bronze', models.IntegerField(default=0)),
                ('picture', models.ImageField(blank=True, upload_to='athlete_images')),
            ],
        ),
    ]
