# Generated by Django 2.2 on 2020-01-05 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='club',
            field=models.CharField(choices=[('SKAA', 'Arrianna Academy'), ('BSKU', 'Bangladesh Shitoryu Karate-do Union')], max_length=100),
        ),
    ]
