# Generated by Django 2.2 on 2020-04-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_auto_20200413_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='individual_kata_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='athlete',
            name='individual_kumite_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='athlete',
            name='team_kata_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='athlete',
            name='team_kumite_active',
            field=models.BooleanField(default=False),
        ),
    ]
