# Generated by Django 2.2 on 2020-01-05 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_auto_20200106_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male')], max_length=100),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='team',
            field=models.CharField(choices=[('BA', 'Bangladesh Army'), ('AVDP', 'Bangladesh Ansar & VDP')], max_length=100),
        ),
    ]
