# Generated by Django 2.2 on 2020-04-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0004_auto_20200420_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='individual_kata_event',
            field=models.CharField(blank=True, choices=[('Male Individual Kata', 'Male Individual Kata'), ('Female Individual Kata', 'Female Individual Kata')], default='', max_length=22),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='individual_kumite_event',
            field=models.CharField(blank=True, choices=[('-50kg Male Kumite', '-50kg Male Kumite'), ('-55kg Male Kumite', '-55kg Male Kumite'), ('-60kg Male Kumite', '-60kg Male Kumite'), ('-67kg Male Kumite', '-67kg Male Kumite'), ('-75kg Male Kumite', '-75kg Male Kumite'), ('-84kg Male Kumite', '-84kg Male Kumite'), ('+84kg Male Kumite', '+84kg Male Kumite'), ('-45kg Female Kumite', '-45kg Female Kumite'), ('-50kg Female Kumite', '-50kg Female Kumite'), ('-55kg Female Kumite', '-55kg Female Kumite'), ('-61kg Female Kumite', '-61kg Female Kumite'), ('-68kg Female Kumite', '-68kg Female Kumite'), ('+68kg Female Kumite', '+68kg Female Kumite')], default='', max_length=22),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='team_kata_event',
            field=models.CharField(blank=True, choices=[('Male Team Kata', 'Male Team Kata'), ('Female Team Kata', 'Female Team Kata')], default='', max_length=22),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='team_kumite_event',
            field=models.CharField(blank=True, choices=[('Male Team Kumite', 'Male Team Kumite'), ('Female Team Kumite', 'Female Team Kumite')], default='', max_length=22),
        ),
    ]
