# Generated by Django 2.2 on 2020-01-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0005_auto_20200106_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='club',
            field=models.CharField(choices=[('BSKU', 'Bangladesh Shitoryu Karate-do Union'), ('SKAA', 'Arrianna Academy')], max_length=100),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='team',
            field=models.CharField(choices=[('BA', 'Bangladesh Army'), ('AVDP', 'Bangladesh Ansar & VDP')], max_length=100),
        ),
    ]
