# Generated by Django 2.2 on 2020-01-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0007_auto_20200106_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='club',
            field=models.CharField(choices=[('SKAA', 'Arrianna Academy'), ('BSKU', 'Bangladesh Shitoryu Karate-do Union')], max_length=100),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=100),
        ),
    ]
