# Generated by Django 2.2 on 2020-04-20 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0009_auto_20200421_0226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Championship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('start_data', models.DateField()),
                ('description', models.CharField(max_length=100)),
                ('logo_picture', models.ImageField(blank=True, upload_to='championship_logos')),
            ],
        ),
        migrations.AlterField(
            model_name='athlete',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=100),
        ),
        migrations.CreateModel(
            name='ChampionshipStanding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[(1, 'Gold'), (2, 'Silver'), (3, 'Bronze')], max_length=7)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.Athlete')),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.Championship')),
            ],
        ),
    ]
