# Generated by Django 2.2 on 2020-04-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0010_auto_20200421_0301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='championship',
            old_name='start_data',
            new_name='start_date',
        ),
        migrations.AlterField(
            model_name='athlete',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100),
        ),
    ]
