# Generated by Django 2.2 on 2020-01-05 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0011_auto_20200106_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='feet_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='athlete',
            name='inch_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='athlete',
            name='weight',
            field=models.FloatField(default=0.0, help_text='Weight in kg'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=100),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='team',
            field=models.CharField(choices=[('AVDP', 'Bangladesh Ansar & VDP'), ('BA', 'Bangladesh Army')], max_length=100),
        ),
    ]
