# Generated by Django 2.2 on 2020-01-05 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0012_auto_20200106_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='club',
            field=models.CharField(choices=[('Arrianna Academy', 'SKAA'), ('Bangladesh Shitoryu Karate-do Union', 'Bangladesh Shitoryu Karate-do Union')], max_length=100),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100),
        ),
    ]
