# Generated by Django 2.2 on 2020-03-18 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0013_auto_20200106_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='individual_kata_event',
            field=models.CharField(choices=[('', '')], default='None', max_length=22),
        ),
        migrations.AddField(
            model_name='athlete',
            name='individual_kumite_event',
            field=models.CharField(choices=[('', '')], default='None', max_length=22),
        ),
        migrations.AddField(
            model_name='athlete',
            name='team_kata_event',
            field=models.CharField(choices=[('', '')], default='None', max_length=22),
        ),
        migrations.AddField(
            model_name='athlete',
            name='team_kumite_event',
            field=models.CharField(choices=[('', '')], default='None', max_length=22),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='club',
            field=models.CharField(choices=[('Arrianna Academy', 'Arrianna Academy'), ('Bangladesh Shitoryu Karate-do Union', 'Bangladesh Shitoryu Karate-do Union')], max_length=100),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='team',
            field=models.CharField(choices=[('Bangladesh Army', 'Bangladesh Army'), ('Bangladesh Ansar & VDP', 'Bangladesh Ansar & VDP')], max_length=100),
        ),
    ]
