# Generated by Django 2.2 on 2020-03-18 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0015_auto_20200318_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='team',
            field=models.CharField(choices=[('Bangladesh Ansar & VDP', 'Bangladesh Ansar & VDP'), ('Bangladesh Army', 'Bangladesh Army')], max_length=100),
        ),
    ]
