# Generated by Django 2.2 on 2020-04-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0018_auto_20200421_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
