# Generated by Django 2.2 on 2021-01-12 00:40

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import django_address.fields


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0022_auto_20210112_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='address',
            field=django_address.fields.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.DJANGO_ADDRESS_ADDRESS_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='address',
            field=django_address.fields.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.DJANGO_ADDRESS_ADDRESS_MODEL),
        ),
    ]
