# Generated by Django 2.2 on 2021-01-12 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0023_auto_20210112_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
