# Generated by Django 2.2 on 2021-01-12 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0024_auto_20210112_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=100),
        ),
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
