# Generated by Django 2.2 on 2021-01-13 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0025_auto_20210113_0510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='championship',
            old_name='title',
            new_name='name',
        ),
    ]
